name = input("Enter your name: ")
gender = input("Enter your gender: ")
age = int(input("Enter your age: "))
branch = input("Enter your branch: ")
course = input("Enter your course: ")
email = input("Enter your email: ")
phone_no= int(input("Enter your phone: "))
city = input("Enter your city: ")
address = input("Enter your address: ")

print("\n")
print("Personal Details")

print("Name : ",name)
print("Gender : ",gender)
print("Age : ",age)
print("Branch : ",branch)
print("Course : ",course)
print("Email : ",email)
print("Phone No : ",phone_no)
print("City : ",city)
print("Address : ",address)
